<?php

namespace Database\Seeders;

use App\Models\AcademicSetting;
use App\Models\AcademicYear;
use App\Models\Batch;
use App\Models\Campus;
use App\Models\Course;
use App\Models\Department;
use App\Models\Program;
use App\Models\SchoolClass;
use App\Models\Section;
use App\Models\Semester;
use App\Models\Subject;
use Illuminate\Database\Seeder;

class AcademicStructureSeeder extends Seeder
{
    public function run(): void
    {
        // 3 campuses
        $campuses = [
            [
                'name' => 'Main Campus',
                'code' => 'CMP-MAIN',
                'institution_type' => 'University',
                'description' => 'Flagship campus hosting all undergraduate and postgraduate faculties.',
                'street_address' => '1 University Avenue',
                'city' => 'Lahore',
                'state_province' => 'Punjab',
                'founded_year' => 1995,
                'status' => 'active',
                'enable_online_admissions' => true,
                'centralized_fee_collection' => true,
                'hostel_management' => true,
                'primary_bank_name' => 'National Bank',
                'bank_account_number' => '0001234567890',
                'bank_swift_code' => 'NBPAPKKA',
            ],
            [
                'name' => 'City Campus',
                'code' => 'CMP-CITY',
                'institution_type' => 'College',
                'description' => 'Downtown college campus focused on business and IT programs.',
                'street_address' => '45 Mall Road',
                'city' => 'Karachi',
                'state_province' => 'Sindh',
                'founded_year' => 2005,
                'status' => 'active',
                'enable_online_admissions' => true,
                'centralized_fee_collection' => false,
                'hostel_management' => false,
                'primary_bank_name' => 'Habib Bank',
                'bank_account_number' => '0009876543210',
                'bank_swift_code' => 'HABBPKKA',
            ],
            [
                'name' => 'North Campus',
                'code' => 'CMP-NORTH',
                'institution_type' => 'School',
                'description' => 'Secondary school campus offering primary and higher secondary education.',
                'street_address' => '12 Hill View Road',
                'city' => 'Islamabad',
                'state_province' => 'Capital Territory',
                'founded_year' => 2012,
                'status' => 'active',
                'enable_online_admissions' => false,
                'centralized_fee_collection' => true,
                'hostel_management' => false,
                'primary_bank_name' => 'Allied Bank',
                'bank_account_number' => '0005556667770',
                'bank_swift_code' => 'ABPAPKKA',
            ],
        ];

        $campusModels = collect($campuses)->map(fn ($c) => Campus::create($c));

        // 3 departments
        $departments = [
            [
                'name' => 'Computer Science',
                'code' => 'DEP-CS',
                'description' => 'Department of Computer Science and Software Engineering.',
                'institution_type' => 'University',
                'campus_id' => $campusModels[0]->id,
                'hod_user_id' => 1,
                'semester_system' => true,
                'credit_hour_system' => true,
                'is_active' => true,
                'allow_admissions' => true,
            ],
            [
                'name' => 'Business Administration',
                'code' => 'DEP-BBA',
                'description' => 'Department of Business and Management Sciences.',
                'institution_type' => 'College',
                'campus_id' => $campusModels[1]->id,
                'hod_user_id' => 2,
                'semester_system' => true,
                'credit_hour_system' => true,
                'is_active' => true,
                'allow_admissions' => true,
            ],
            [
                'name' => 'Electrical Engineering',
                'code' => 'DEP-EE',
                'description' => 'Department of Electrical and Electronics Engineering.',
                'institution_type' => 'University',
                'campus_id' => $campusModels[0]->id,
                'hod_user_id' => 3,
                'semester_system' => true,
                'credit_hour_system' => true,
                'is_active' => true,
                'allow_admissions' => true,
            ],
        ];

        $departmentModels = collect($departments)->map(fn ($d) => Department::create($d));

        // 3 programs
        $programs = [
            [
                'name' => 'BS Computer Science',
                'code' => 'PRG-BSCS',
                'degree_level' => 'Bachelor',
                'department_id' => $departmentModels[0]->id,
                'faculty' => 'Faculty of Computing',
                'multi_department_access' => false,
                'total_years' => 4.0,
                'total_semesters' => 8,
                'total_credits' => 130,
                'coordinator_user_id' => 1,
                'allow_admissions' => true,
                'lock_structure' => false,
                'status' => 'active',
            ],
            [
                'name' => 'Bachelor of Business Administration',
                'code' => 'PRG-BBA',
                'degree_level' => 'Bachelor',
                'department_id' => $departmentModels[1]->id,
                'faculty' => 'Faculty of Management',
                'multi_department_access' => true,
                'total_years' => 4.0,
                'total_semesters' => 8,
                'total_credits' => 124,
                'coordinator_user_id' => 2,
                'allow_admissions' => true,
                'lock_structure' => false,
                'status' => 'active',
            ],
            [
                'name' => 'MS Electrical Engineering',
                'code' => 'PRG-MSEE',
                'degree_level' => 'Master',
                'department_id' => $departmentModels[2]->id,
                'faculty' => 'Faculty of Engineering',
                'multi_department_access' => false,
                'total_years' => 2.0,
                'total_semesters' => 4,
                'total_credits' => 30,
                'coordinator_user_id' => 3,
                'allow_admissions' => true,
                'lock_structure' => false,
                'status' => 'active',
            ],
        ];

        $programModels = collect($programs)->map(fn ($p) => Program::create($p));

        // 3 academic years
        $academicYears = [
            [
                'name' => '2024-2025',
                'start_date' => '2024-09-01',
                'end_date' => '2025-06-30',
                'scope' => 'all_campuses',
                'status' => 'completed',
                'link_fee_structure' => true,
                'auto_roll_attendance' => false,
                'fees_configured' => true,
                'exams_configured' => true,
                'attendance_enabled' => true,
                'prevent_date_overlap' => true,
            ],
            [
                'name' => '2025-2026',
                'start_date' => '2025-09-01',
                'end_date' => '2026-06-30',
                'scope' => 'all_campuses',
                'status' => 'active',
                'link_fee_structure' => true,
                'auto_roll_attendance' => true,
                'fees_configured' => true,
                'exams_configured' => true,
                'attendance_enabled' => true,
                'prevent_date_overlap' => true,
            ],
            [
                'name' => '2026-2027',
                'start_date' => '2026-09-01',
                'end_date' => '2027-06-30',
                'scope' => 'specific_campuses',
                'status' => 'upcoming',
                'link_fee_structure' => true,
                'auto_roll_attendance' => false,
                'fees_configured' => false,
                'exams_configured' => false,
                'attendance_enabled' => false,
                'prevent_date_overlap' => true,
            ],
        ];

        $academicYearModels = collect($academicYears)->map(fn ($y) => AcademicYear::create($y));

        // 3 semesters
        $semesters = [
            [
                'name' => 'Fall 2025',
                'code' => 'SEM-FA25',
                'description' => 'Fall semester for the 2025-2026 academic year.',
                'program_id' => $programModels[0]->id,
                'department_id' => $departmentModels[0]->id,
                'campus_id' => $campusModels[0]->id,
                'academic_year_id' => $academicYearModels[1]->id,
                'start_date' => '2025-09-01',
                'end_date' => '2026-01-15',
                'total_credit_hours' => 18,
                'generate_fee_plan' => true,
                'late_fee_rule' => 'flat_500',
                'grading_system' => 'GPA (4.0 Scale)',
                'is_locked' => false,
                'fee_cycle_generated' => true,
                'exam_cycle_generated' => false,
                'status' => 'active',
            ],
            [
                'name' => 'Spring 2026',
                'code' => 'SEM-SP26',
                'description' => 'Spring semester for the 2025-2026 academic year.',
                'program_id' => $programModels[1]->id,
                'department_id' => $departmentModels[1]->id,
                'campus_id' => $campusModels[1]->id,
                'academic_year_id' => $academicYearModels[1]->id,
                'start_date' => '2026-02-01',
                'end_date' => '2026-06-30',
                'total_credit_hours' => 16,
                'generate_fee_plan' => true,
                'late_fee_rule' => 'percentage_2',
                'grading_system' => 'GPA (4.0 Scale)',
                'is_locked' => false,
                'fee_cycle_generated' => false,
                'exam_cycle_generated' => false,
                'status' => 'upcoming',
            ],
            [
                'name' => 'Fall 2026',
                'code' => 'SEM-FA26',
                'description' => 'Fall semester for the 2026-2027 academic year.',
                'program_id' => $programModels[2]->id,
                'department_id' => $departmentModels[2]->id,
                'campus_id' => $campusModels[0]->id,
                'academic_year_id' => $academicYearModels[2]->id,
                'start_date' => '2026-09-01',
                'end_date' => '2027-01-15',
                'total_credit_hours' => 12,
                'generate_fee_plan' => true,
                'late_fee_rule' => 'flat_1000',
                'grading_system' => 'GPA (4.0 Scale)',
                'is_locked' => false,
                'fee_cycle_generated' => false,
                'exam_cycle_generated' => false,
                'status' => 'upcoming',
            ],
        ];

        $semesterModels = collect($semesters)->map(fn ($s) => Semester::create($s));

        // 3 classes
        $classes = [
            [
                'name' => 'BSCS Year 1',
                'code' => 'CLS-BSCS1',
                'description' => 'First-year cohort for BS Computer Science.',
                'institution_type' => 'University',
                'academic_level' => 'Undergraduate',
                'board' => 'HEC',
                'campus_id' => $campusModels[0]->id,
                'semester_id' => $semesterModels[0]->id,
                'coordinator_user_id' => 1,
                'batch_count' => 2,
                'total_credit_hours' => 18,
                'multi_campus_sharing' => false,
                'is_active' => true,
                'allow_admissions' => true,
                'status' => 'active',
            ],
            [
                'name' => 'BBA Year 1',
                'code' => 'CLS-BBA1',
                'description' => 'First-year cohort for BBA.',
                'institution_type' => 'College',
                'academic_level' => 'Undergraduate',
                'board' => 'HEC',
                'campus_id' => $campusModels[1]->id,
                'semester_id' => $semesterModels[1]->id,
                'coordinator_user_id' => 2,
                'batch_count' => 1,
                'total_credit_hours' => 16,
                'multi_campus_sharing' => false,
                'is_active' => true,
                'allow_admissions' => true,
                'status' => 'active',
            ],
            [
                'name' => 'Grade 9',
                'code' => 'CLS-G9',
                'description' => 'Secondary school grade 9 class.',
                'institution_type' => 'School',
                'academic_level' => 'Secondary',
                'board' => 'Federal Board',
                'campus_id' => $campusModels[2]->id,
                'semester_id' => $semesterModels[2]->id,
                'coordinator_user_id' => 3,
                'batch_count' => 3,
                'total_credit_hours' => null,
                'multi_campus_sharing' => false,
                'is_active' => true,
                'allow_admissions' => true,
                'status' => 'active',
            ],
        ];

        $classModels = collect($classes)->map(fn ($c) => SchoolClass::create($c));

        // 3 sections
        $sections = [
            [
                'name' => 'Section A',
                'code' => 'SEC-BSCS1-A',
                'section_type' => 'Morning',
                'class_id' => $classModels[0]->id,
                'campus_id' => $campusModels[0]->id,
                'institution_type' => 'University',
                'max_capacity' => 50,
                'current_enrollment' => 42,
                'enable_waitlist' => true,
                'class_teacher_id' => 1,
                'is_active' => true,
                'allow_admissions' => true,
                'lock_structure' => false,
                'status' => 'active',
            ],
            [
                'name' => 'Section B',
                'code' => 'SEC-BBA1-B',
                'section_type' => 'Evening',
                'class_id' => $classModels[1]->id,
                'campus_id' => $campusModels[1]->id,
                'institution_type' => 'College',
                'max_capacity' => 40,
                'current_enrollment' => 35,
                'enable_waitlist' => true,
                'class_teacher_id' => 2,
                'is_active' => true,
                'allow_admissions' => true,
                'lock_structure' => false,
                'status' => 'active',
            ],
            [
                'name' => 'Section C',
                'code' => 'SEC-G9-C',
                'section_type' => 'Morning',
                'class_id' => $classModels[2]->id,
                'campus_id' => $campusModels[2]->id,
                'institution_type' => 'School',
                'max_capacity' => 30,
                'current_enrollment' => 28,
                'enable_waitlist' => false,
                'class_teacher_id' => 3,
                'is_active' => true,
                'allow_admissions' => true,
                'lock_structure' => false,
                'status' => 'active',
            ],
        ];

        collect($sections)->each(fn ($s) => Section::create($s));

        // 5 subjects
        $subjects = [
            [
                'name' => 'Programming Fundamentals',
                'code' => 'SUB-PF',
                'classification' => 'Core',
                'institution_type' => 'University',
                'department_id' => $departmentModels[0]->id,
                'class_id' => $classModels[0]->id,
                'semester_id' => $semesterModels[0]->id,
                'credits' => 3.0,
                'total_marks' => 100,
                'weight_mid' => 30,
                'weight_final' => 50,
                'primary_teacher_id' => 1,
                'curriculum_focus' => 'Introduction to structured programming in C++.',
                'prerequisites_required' => false,
                'lock_structural_changes' => false,
                'status' => 'active',
            ],
            [
                'name' => 'Data Structures',
                'code' => 'SUB-DS',
                'classification' => 'Core',
                'institution_type' => 'University',
                'department_id' => $departmentModels[0]->id,
                'class_id' => $classModels[0]->id,
                'semester_id' => $semesterModels[0]->id,
                'credits' => 4.0,
                'total_marks' => 100,
                'weight_mid' => 30,
                'weight_final' => 50,
                'primary_teacher_id' => 1,
                'curriculum_focus' => 'Linear and non-linear data structures and algorithms.',
                'prerequisites_required' => true,
                'lock_structural_changes' => false,
                'status' => 'active',
            ],
            [
                'name' => 'Principles of Management',
                'code' => 'SUB-POM',
                'classification' => 'Core',
                'institution_type' => 'College',
                'department_id' => $departmentModels[1]->id,
                'class_id' => $classModels[1]->id,
                'semester_id' => $semesterModels[1]->id,
                'credits' => 3.0,
                'total_marks' => 100,
                'weight_mid' => 30,
                'weight_final' => 50,
                'primary_teacher_id' => 2,
                'curriculum_focus' => 'Foundations of management theory and practice.',
                'prerequisites_required' => false,
                'lock_structural_changes' => false,
                'status' => 'active',
            ],
            [
                'name' => 'Financial Accounting',
                'code' => 'SUB-FA',
                'classification' => 'Elective',
                'institution_type' => 'College',
                'department_id' => $departmentModels[1]->id,
                'class_id' => $classModels[1]->id,
                'semester_id' => $semesterModels[1]->id,
                'credits' => 3.0,
                'total_marks' => 100,
                'weight_mid' => 30,
                'weight_final' => 50,
                'primary_teacher_id' => 2,
                'curriculum_focus' => 'Recording and reporting of financial transactions.',
                'prerequisites_required' => false,
                'lock_structural_changes' => false,
                'status' => 'active',
            ],
            [
                'name' => 'General Mathematics',
                'code' => 'SUB-MATH9',
                'classification' => 'Core',
                'institution_type' => 'School',
                'department_id' => $departmentModels[2]->id,
                'class_id' => $classModels[2]->id,
                'semester_id' => $semesterModels[2]->id,
                'credits' => 2.0,
                'total_marks' => 100,
                'weight_mid' => 30,
                'weight_final' => 50,
                'primary_teacher_id' => 3,
                'curriculum_focus' => 'Algebra, geometry and trigonometry for grade 9.',
                'prerequisites_required' => false,
                'lock_structural_changes' => false,
                'status' => 'active',
            ],
        ];

        collect($subjects)->each(fn ($s) => Subject::create($s));

        // 5 courses
        $courses = [
            [
                'name' => 'Introduction to Programming',
                'code' => 'CRS-CS101',
                'type' => 'Core',
                'description' => 'Hands-on introductory programming course.',
                'campus_id' => $campusModels[0]->id,
                'program_id' => $programModels[0]->id,
                'department_id' => $departmentModels[0]->id,
                'semester_id' => $semesterModels[0]->id,
                'credit_hours' => 3,
                'total_marks' => 100,
                'passing_percentage' => 50,
                'weight_quiz' => 10,
                'weight_assignment' => 15,
                'weight_mid' => 25,
                'weight_final' => 50,
                'primary_instructor_id' => 1,
                'is_active' => true,
                'open_enrollment' => true,
                'status' => 'active',
            ],
            [
                'name' => 'Object Oriented Programming',
                'code' => 'CRS-CS102',
                'type' => 'Core',
                'description' => 'OOP concepts using C++ and Java.',
                'campus_id' => $campusModels[0]->id,
                'program_id' => $programModels[0]->id,
                'department_id' => $departmentModels[0]->id,
                'semester_id' => $semesterModels[0]->id,
                'credit_hours' => 4,
                'total_marks' => 100,
                'passing_percentage' => 50,
                'weight_quiz' => 10,
                'weight_assignment' => 15,
                'weight_mid' => 25,
                'weight_final' => 50,
                'primary_instructor_id' => 1,
                'is_active' => true,
                'open_enrollment' => true,
                'status' => 'active',
            ],
            [
                'name' => 'Database Lab',
                'code' => 'CRS-CS103L',
                'type' => 'Lab',
                'description' => 'Practical database design and SQL lab.',
                'campus_id' => $campusModels[0]->id,
                'program_id' => $programModels[0]->id,
                'department_id' => $departmentModels[0]->id,
                'semester_id' => $semesterModels[0]->id,
                'credit_hours' => 1,
                'total_marks' => 100,
                'passing_percentage' => 50,
                'weight_quiz' => 10,
                'weight_assignment' => 15,
                'weight_mid' => 25,
                'weight_final' => 50,
                'primary_instructor_id' => 1,
                'is_active' => true,
                'open_enrollment' => true,
                'status' => 'active',
            ],
            [
                'name' => 'Marketing Management',
                'code' => 'CRS-BBA201',
                'type' => 'Elective',
                'description' => 'Strategic marketing for business students.',
                'campus_id' => $campusModels[1]->id,
                'program_id' => $programModels[1]->id,
                'department_id' => $departmentModels[1]->id,
                'semester_id' => $semesterModels[1]->id,
                'credit_hours' => 3,
                'total_marks' => 100,
                'passing_percentage' => 50,
                'weight_quiz' => 10,
                'weight_assignment' => 15,
                'weight_mid' => 25,
                'weight_final' => 50,
                'primary_instructor_id' => 2,
                'is_active' => true,
                'open_enrollment' => true,
                'status' => 'active',
            ],
            [
                'name' => 'Power Systems',
                'code' => 'CRS-EE501',
                'type' => 'General',
                'description' => 'Graduate-level power systems analysis.',
                'campus_id' => $campusModels[0]->id,
                'program_id' => $programModels[2]->id,
                'department_id' => $departmentModels[2]->id,
                'semester_id' => $semesterModels[2]->id,
                'credit_hours' => 3,
                'total_marks' => 100,
                'passing_percentage' => 50,
                'weight_quiz' => 10,
                'weight_assignment' => 15,
                'weight_mid' => 25,
                'weight_final' => 50,
                'primary_instructor_id' => 3,
                'is_active' => true,
                'open_enrollment' => false,
                'status' => 'active',
            ],
        ];

        collect($courses)->each(fn ($c) => Course::create($c));

        // 3 batches
        $batches = [
            [
                'name' => 'BSCS Fall 2025 Batch',
                'code' => 'BAT-BSCS-F25',
                'batch_type' => 'Regular',
                'description' => 'Morning batch for incoming BSCS students.',
                'status' => 'active',
                'institution_type' => 'University',
                'campus_id' => $campusModels[0]->id,
                'program_id' => $programModels[0]->id,
                'class_id' => $classModels[0]->id,
                'semester_id' => $semesterModels[0]->id,
                'start_date' => '2025-09-01',
                'end_date' => '2026-01-15',
                'weekly_days' => ['Monday', 'Wednesday', 'Friday'],
                'max_students' => 50,
                'allow_waitlist' => true,
                'primary_instructor_id' => 1,
                'fee_plan_id' => 1,
                'attendance_tracking' => 'per_lecture',
                'installments_allowed' => true,
                'open_for_admissions' => true,
            ],
            [
                'name' => 'BBA Spring 2026 Batch',
                'code' => 'BAT-BBA-S26',
                'batch_type' => 'Evening',
                'description' => 'Evening batch for BBA program.',
                'status' => 'active',
                'institution_type' => 'College',
                'campus_id' => $campusModels[1]->id,
                'program_id' => $programModels[1]->id,
                'class_id' => $classModels[1]->id,
                'semester_id' => $semesterModels[1]->id,
                'start_date' => '2026-02-01',
                'end_date' => '2026-06-30',
                'weekly_days' => ['Tuesday', 'Thursday', 'Saturday'],
                'max_students' => 40,
                'allow_waitlist' => true,
                'primary_instructor_id' => 2,
                'fee_plan_id' => 2,
                'attendance_tracking' => 'daily',
                'installments_allowed' => true,
                'open_for_admissions' => true,
            ],
            [
                'name' => 'MSEE Fall 2026 Batch',
                'code' => 'BAT-MSEE-F26',
                'batch_type' => 'Weekend',
                'description' => 'Weekend batch for MS Electrical Engineering.',
                'status' => 'upcoming',
                'institution_type' => 'University',
                'campus_id' => $campusModels[0]->id,
                'program_id' => $programModels[2]->id,
                'class_id' => $classModels[2]->id,
                'semester_id' => $semesterModels[2]->id,
                'start_date' => '2026-09-01',
                'end_date' => '2027-01-15',
                'weekly_days' => ['Saturday', 'Sunday'],
                'max_students' => 25,
                'allow_waitlist' => false,
                'primary_instructor_id' => 3,
                'fee_plan_id' => 3,
                'attendance_tracking' => 'per_session',
                'installments_allowed' => false,
                'open_for_admissions' => true,
            ],
        ];

        collect($batches)->each(fn ($b) => Batch::create($b));

        // 1 academic_settings row
        AcademicSetting::create([
            'academic_year_id' => $academicYearModels[1]->id,
            'grading_system' => 'GPA (4.0 Scale)',
            'pass_mark_threshold' => 40,
            'min_attendance_required' => 75,
            'attendance_grace_minutes' => 15,
            'attendance_session_limit' => '3_per_day',
            'attendance_warning_threshold' => 75,
            'attendance_critical_threshold' => 60,
            'exam_structure' => 'Semester Structure',
            'weight_final' => 50,
            'weight_midterm' => 30,
            'weight_assignments_lab' => 10,
            'weight_quizzes' => 10,
            'approval_workflow' => ['teacher', 'hod', 'registrar'],
            'promotion_enabled' => true,
            'promotion_min_gpa' => 2.00,
            'promotion_max_fail_subjects' => 2,
            'university_mode_enabled' => true,
            'min_credit_load' => 12,
            'max_credit_load' => 21,
            'year_start_month' => 'September',
            'makeup_class_allowance' => 'within_2_weeks',
        ]);
    }
}
