import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './resources/**/*.blade.php',
        './resources/**/*.js',
        './resources/**/*.vue',
        './config/navigation.php',
    ],
    // Color utilities built from runtime data (e.g. dashboard KPI tones) — keep them.
    safelist: [
        'bg-primary/10', 'text-primary',
        'bg-tertiary/10', 'text-tertiary',
        'bg-error/10', 'text-error',
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                'primary': '#004ac6',
                'primary-container': '#2563eb',
                'on-primary': '#ffffff',
                'on-primary-container': '#eeefff',
                'primary-fixed': '#dbe1ff',
                'primary-fixed-dim': '#b4c5ff',
                'secondary': '#505f76',
                'secondary-container': '#d0e1fb',
                'on-secondary': '#ffffff',
                'on-secondary-container': '#54647a',
                'tertiary': '#006242',
                'tertiary-container': '#007d55',
                'on-tertiary': '#ffffff',
                'error': '#ba1a1a',
                'error-container': '#ffdad6',
                'on-error': '#ffffff',
                'on-error-container': '#93000a',
                'background': '#f7f9fb',
                'on-background': '#191c1e',
                'surface': '#f7f9fb',
                'surface-dim': '#d8dadc',
                'surface-bright': '#f7f9fb',
                'surface-container-lowest': '#ffffff',
                'surface-container-low': '#f2f4f6',
                'surface-container': '#eceef0',
                'surface-container-high': '#e6e8ea',
                'surface-container-highest': '#e0e3e5',
                'surface-variant': '#e0e3e5',
                'on-surface': '#191c1e',
                'on-surface-variant': '#434655',
                'outline': '#737686',
                'outline-variant': '#c3c6d7',
                'inverse-surface': '#2d3133',
                'inverse-on-surface': '#eff1f3',
                'inverse-primary': '#b4c5ff',
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                lg: '0.5rem',
                xl: '0.75rem',
                full: '9999px',
            },
            spacing: {
                xs: '4px',
                sm: '8px',
                base: '4px',
                md: '16px',
                lg: '24px',
                xl: '32px',
                gutter: '20px',
                'container-max': '1440px',
            },
            fontFamily: {
                sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
                'body-md': ['Inter'],
                'body-lg': ['Inter'],
                'label-sm': ['Inter'],
                'label-md': ['Inter'],
                'headline-md': ['Inter'],
                'headline-lg': ['Inter'],
                'display-lg': ['Inter'],
            },
            fontSize: {
                'label-sm': ['11px', { lineHeight: '14px', fontWeight: '500' }],
                'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '600' }],
                'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
                'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
                'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
                'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
            },
        },
    },
    plugins: [
        forms,
        containerQueries,
    ],
};
